apiVersion: v1
kind: ReplicationController
metadata:
  name: jenkins-master-controller
spec:
  replicas: 1
  selector:
    app: jenkins-master
  template:
    metadata:
      labels:
        app: jenkins-master
    spec:
      containers:
      - name: jenkins-master
        image: fgimenez/snappy-jenkins
        ports:
        - containerPort: 8080
        securityContext:
          privileged: true
        volumeMounts:
        - name: jenkins-master-data
          mountPath: /var/jenkins_home
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 5
      volumes:
      - name: jenkins-master-data
        emptyDir: {}
