apiVersion: v1
kind: Service
metadata:
  name: jenkins-proxy-service
spec:
  type: NodePort
  selector:
    app: jenkins-proxy
  ports:
  - name: http
    port: 8081
    targetPort: 80
    protocol: TCP