apiVersion: v1
kind: ReplicationController
metadata:
  name: jenkins-proxy-controller
spec:
  replicas: 1
  selector:
    app: jenkins-proxy
  template:
    metadata:
      labels:
        app: jenkins-proxy
    spec:
      containers:
      - name: jenkins-proxy
        image: fgimenez/snappy-jenkins-proxy
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          timeoutSeconds: 5
